version: '3.7'

# Networks
networks:
  # Internal network
  docker-envnet:
    driver: bridge

volumes:
  docker-env-mysql-data:
    driver: local

# Services
services:

  # Nginx
  docker-env-nginx:
    image: nginx:latest
    container_name: docker-env-nginx
    networks:
      docker-envnet:
        aliases:
          - dockerenv.desenv
    working_dir: /var/www
    volumes:
      - ..:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "443:443"
    
  docker-env-php81-fpm:
    build:
      context: .
      dockerfile: ./php81/Dockerfile
    container_name: docker-env-php81-fpm
    volumes:
      - ..:/var/www/
    networks:
      - docker-envnet

  docker-env-mysql:
    image: mysql:latest
    container_name: docker-env-mysql
    networks:
      - docker-envnet
    volumes:
      - docker-env-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dockerenv_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dockerenv_user
      - MYSQL_PASSWORD=dockerenv_password
      - MYSQL_TCP_PORT=3308
    ports:
      - "3308:3308"
